# 2022/06/12

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: true
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
