# 2023/05/10

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: false
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
