# 2022/06/12

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: false

  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
    mutableTypes: [
      'kotlin.collections.MutableList',
      'kotlin.collections.MutableMap',
      'kotlin.collections.MutableSet',
      'java.util.ArrayList',
      'java.util.LinkedHashSet',
      'java.util.HashSet',
      'java.util.LinkedHashMap',
      'java.util.HashMap'
    ]
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
    restrictToAnnotatedMethods: false
    ignoreFunctionCall: [
      kotlin.collections.MutableList.add,
      kotlin.collections.MutableSet.add,
      kotlin.collections.MutableSet.addAll,
      kotlin.collections.removeAll,
      kotlin.error,
      kotlin.TODO,
      kotlinx.coroutines.launch,
      kotlinx.coroutines.withContext
    ]
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
    ignoreAnnotated: []
    ignoreOnClassesPattern: ''
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  MissingWhenCase:
    allowElseExpression: true
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  RedundantElseInWhen:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true # todo https://github.com/detekt/detekt/issues/4617
  WrongEqualsTypeParameter:
    active: true
